#ifndef _BS_SENSOR_APP_CMD_H_
#define _BS_SENSOR_APP_CMD_H_

#include "AppCmd.h"

#define CMD_UPLOAD_SENSOR_VALUE				0x0031
#define CMD_CIRCULARLY_UPLOAD_SENSOR_VALUE	0x0032
#define CMD_STOP_UPLOAD_SENSOR_VALUE		0x0033
#define CMD_SET_CIRCULARLY_UPLOAD_INTERVAL	0x0034	//带2个byte参数，表示unsigned int的interval数值

//UPLOAD_INDEX与平台的sensorID对应
#define UPLOAD_INDEX_OUT_TEMPERATURE		0x0001
#define UPLOAD_INDEX_OUT_HUMIDITY			0x0002
#define UPLOAD_INDEX_OUT_HEAT				0x0003
#define UPLOAD_INDEX_IN_TEMPERATURE			0x0004
#define UPLOAD_INDEX_IN_HUMIDITY			0x0005
#define UPLOAD_INDEX_IN_HEAT				0x0006
#define UPLOAD_INDEX_SOLID_HUMIDITY			0x0007
#define UPLOAD_INDEX_DUST_DENSITY			0x0008
#define UPLOAD_INDEX_LIGHT_INTENSITY		0x0009
#define UPLOAD_INDEX_HARMFUL_GAS			0x000a
#define UPLOAD_INDEX_FIRE					0x000b


#endif